dist: xenial
sudo: required

language: node_js
node_js: node

install:
  - npm install
  - npm install -g @angular/cli
  - npm install -g firebase-tools

jobs:
  include:
    - name: Job timbrage
      before_install:
        - chmod +x $SCRIPT_DIR/check_changes
        - check_changes apps/timbrage libs/commons package-lock.json || travis_terminate 0;
      script: ng build --prod --project timbrage
      deploy:
        provider: script
        script: firebase deploy --only hosting:timbrage
        skip_cleanup: true

    - name: Job admin
      before_install:
        - chmod +x $SCRIPT_DIR/check_changes
        - check_changes apps/admin libs/commons package-lock.json || travis_terminate 0;
      script: ng build --prod --project reporting
      deploy:
        provider: script
        script: firebase deploy --only hosting:admin
        skip_cleanup: true

    - name: Job functions
      before_install:
        - chmod +x $SCRIPT_DIR/check_changes
        - check_changes functions || travis_terminate 0;
        - cd functions
      script: npm run build
      deploy:
        provider: script
        script: npm run deploy
        skip_cleanup: true

branches:
  only: master

env:
  global:
    - SCRIPT_DIR="`pwd`/.travis"
    - PATH=$PATH:$SCRIPT_DIR
    - secure: VRYmVbYY2As6XRJEFFsGfXQZLs80WyFj1Ei4xtrUYSBuiasqERUQOzqm8p5ynnmNMh4Q0c9IwrsMyYVnRjHIpkCYYkJ3hZDWw5epTsR3WWgK4cdO5reGufnDtpaAvWl3Sniu9dnKbl2+YiaRiMOll1Xk0DMayTdaRbeF0F/GvcHNRpZpL682gVBELhJ3iMJ/lMUD0iwDD9esMuq/FZzIa60JcTS3Wi4eI8nDhXJVPh7uBFz/T2oOCHLwVzzeUPmivTTYEjdo/mkON6b+B1/7KvofkHJzR1Wo2JJV7PIuyhJiervdr7cnk4aFyiAukEqj8AAzlqSrC3bATDruWYIfvvlACx11LJpS3kgHtMGW8bSdnCMEKqcvF3rJ3FwMDOXMI+xl0DGny+uuCWv5nkwd8bxanJHetLl+T36Uyr6Oi4lBm/WdqJdhp8rrm6NfT3Qqy7zEmK5BnSZGAhKNIryrZ6YZvkb7nKWfEHF9tMtou9RkRsU9OYR0RncGNX3DaSL8mFkegFwMJRzAWm2ZH5t3SPfFTYxfoKiy2foFvPzI6UnHGESKA4aloAqrcN+AYoJIU92TjWG7Sy43GSTk2MjtvTdHEGvWZ7+/cfedOSE1S5yoA2Imo70lg0tnPaUJ4rUWUDRysA+rLQjiNxEe2/6OZpEorOKKxvnD+DGV28SDGuw=
