#mongodb
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: report
  jackson:
    date-format: yyyy-MM-dd HH:mm
  security:
    oauth2:
      client:
        registration:
          google:
            scope: profile
logging:
  level:
    root: info
    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener: ERROR
server:
  error:
    include-stacktrace: always
